### ISSUE TITLE
Current public release apparently unplayable

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#94]
1.4.06, which is the newest version on Armaholic and BIF, can't be run with RHS, ACE, TFAR according to Taki1980:

>Ich habe RHS und Ace und TFAR usw. gestartet. Wenn ich die Mission durchlade dann komme ich immer wieder in den Missionsauswahlbereich zurück ohne Fehlermeldung

**Comment by Fusselwurm** [comment]
`76561197998876051 2016-08-23 23:33:12 Taki1980` <-it's been a while. sadly, all existing server logs seem newer than that.

**Comment by Fusselwurm** [comment]
did he do that on our server or at home @taki1980 plz comment  :sob:

**Comment by McDiod** [comment]
On a private server I guess, since he specifically asked me about version 1.4.06.
Either way the thing is, the release currently available to the public is pretty old and should probably be updated some time.

**Comment by nomisum** [comment]
@Fusselwurm @McDiod 

only known issue is missing radio truck "deploy action" since last arma update. probably BIS fault, its fixed in our current build.

 
my suggestion would be to release a hotfix version as soon possible. i cant imagine why taki cant even start the map though.

further todos before a next major (and probably final) release : 
* revert to basic medic system (urgent todo currently)
* implement better buy menu (based on rattrap, but remade fancy UI)
* parse loadout stuff into setUnitLoadout functions, as this is the most reliable command now and should fix any missing/half missing loadout issues once and for all

**Comment by McDiod** [comment]
#96
